### ISSUE TITLE
401 Error Fetching GitHub Data When Using npm Instead of Local Routing (./src/index.js)

### ISSUE THREAD

**Issue by tommypurcell** [tommypurcell/react-github-profile#2]
When making requests to the GitHub API using the react-github-profile module imported from npm, a 401 Unauthorized error is encountered. The same code works correctly when using a local version of the module (e.g., ./src/index.js).

![Screenshot 2024-06-01 at 12 00 46 PM](https://github.com/tommypurcell/react-github-profile/assets/120073087/66516262-0be7-45e7-9c4f-9f75e501d6e4)

**Comment by tommypurcell** [comment]
Fixed. 

Started working after adding import React to GitHubProfile Component and access tokens were fully removed.

Package is now functional and up and running with npm i react-github-profile

**Comment by grubersjoe** [comment]
Hey Tommy,

great to hear, glad that you got it working!
